- import_role:
    name: openshift_common
    tasks_from: delete_kubernetes_objects.yml
  vars:
    delete_kubernetes_objects:
      - api_version: kubevirt.io/v1
        kind: VirtualMachine
      - api_version: kubevirt.io/v1
        kind: DataVolume
      - api_version: kubevirt.io/v1
        kind: VirtualMachineInstance

- name: Delete OpenShift Virtualization instance
  command: oc delete --kustomize {{ openshift_virtualization_kustomizations.instance }}

- name: Delete OpenShift Virtualization operator (KVM)
  command: oc delete --kustomize {{ openshift_virtualization_kustomizations.operator_kvm }}
  when: qemu_kvm

- name: Delete OpenShift Virtualization operator (emulation)
  command: oc delete --kustomize {{ openshift_virtualization_kustomizations.operator_emu }}
  when: not qemu_kvm
