- name: Deploy OpenShift Virtualization operator
  command: oc apply --kustomize {{ openshift_virtualization_kustomizations.operator }}

- name: Wait for OpenShift Virtualization operator to deploy
  import_role:
    name: openshift_common
    tasks_from: wait_for_operator.yml
  vars:
    subscription_name: '{{ openshift_virtualization_subscription_name }}'
    subscription_namespace: '{{ openshift_virtualization_subscription_namespace }}'

- name: Deploy OpenShift Virtualization instance
  command: oc apply --kustomize {{ openshift_virtualization_kustomizations.instance }}

- name: Waiting since {{ lookup("pipe", "date +%r") }} for {{ openshift_virtualization_instance_name }} deployment to complete
  k8s_info:
    api_version: hco.kubevirt.io/v1beta1
    kind: HyperConverged
    namespace: '{{ openshift_virtualization_instance_namespace }}'
    name: '{{ openshift_virtualization_instance_name }}'
  register: openshift_virtualization_instance
  until:
    - openshift_virtualization_instance.resources.0.status is defined
    - openshift_virtualization_instance.resources.0.status.conditions | selectattr('type', 'equalto', 'Available') | list | length > 0
    - (openshift_virtualization_instance.resources.0.status.conditions | selectattr('type', 'equalto', 'Available') | first).status == "True"
  retries: 60
  delay: 10
