- name: Check if Kubernetes config file exists
  stat:
    path: .kube/config
  register: kubeconfig_stat

- name: Create kubeconfig file if it doesn't exist
  import_tasks: bastion_setup_kubeconfig.yml
  when: not kubeconfig_stat.stat.exists

- name: Don't verify API server cert (cert will be replaced with the Let's Encrypt cert)
  command: oc config set-cluster cluster-{{ otlc_service_info.guid }} --insecure-skip-tls-verify=true
