- name: Obtain infrastructure info
  k8s_info:
    api_version: config.openshift.io/v1
    kind: Infrastructure
    name: cluster
    namespace: ''
  register: infrastructure

- name: Set cluster_id
  set_fact:
    cluster_id: '{{ infrastructure.resources.0.status.infrastructureName }}'

- name: Create cluster autoscaler
  k8s:
    definition: "{{ lookup('template', 'default-clusterautoscaler.yml') }}"

- name: Retrieve existing machinesets
  k8s_info:
    api_version: machine.openshift.io/v1beta1
    kind: MachineSet
    namespace: openshift-machine-api
  register: machinesets_result

- name: Enable autoscaling for the machinesets
  k8s:
    definition: "{{ lookup('template', 'machineautoscaler.yml') }}"
  when: item.metadata.name.startswith(cluster_id)
  loop: '{{ machinesets_result.resources }}'
  loop_control:
    label: '{{ item.metadata.namespace }} {{ item.metadata.name }}'

- name: Deploy Infra Nodes MachineSet
  import_role:
    name: openshift_common
    tasks_from: add_machineset.yml
  when: install_infra_nodes | bool
