apiVersion: autoscaling.openshift.io/v1beta1
kind: MachineAutoscaler
metadata:
  name: '{{ cluster_id }}-worker-{{ aws_region }}{{ item }}'
  namespace: openshift-machine-api
spec:
  minReplicas: 2
  maxReplicas: 12
  scaleTargetRef:
    apiVersion: machine.openshift.io/v1beta1
    kind: MachineSet
    name: '{{ cluster_id }}-worker-{{ aws_region }}{{ item }}'
