apiVersion: cluster.open-cluster-management.io/v1
kind: ManagedCluster
metadata:
  labels:
    cloud: Amazon
    region: {{ rhacm_managed_cluster.aws_region }}
    name: {{ rhacm_managed_cluster.cluster_name }}
    vendor: OpenShift
  name: {{ rhacm_managed_cluster.cluster_name }}
spec:
  hubAcceptsClient: true
