- name: Create virtual machines
  virt:
    command: define
    xml: "{{ lookup('template', 'domain.xml') }}"
  with_dict: '{{ virtual_machines }}'
  become: yes

- name: Create qcow2 disk
  command: qemu-img create -f qcow2 {{ virtual_machines_dir }}/{{ item.key }}.qcow2 {{ item.value.disk_gb }}G
  args:
    creates: '{{ virtual_machines_dir }}/{{ item.key }}.qcow2'
  with_dict: '{{ virtual_machines }}'
  become_user: '{{ virtual_machines_user }}'
  become: yes
