- name: List running virtual machines
  virt:
    command: list_vms
    state: running
  register: libvirt_running_vms
  become: yes

- name: Stop virtual machines
  virt:
    command: destroy
    name: '{{ hostvars[item].ansible_ssh_host }}'
  when: 'virtual_machines[item] is defined and hostvars[item].ansible_ssh_host in libvirt_running_vms.list_vms'
  with_items: '{{ ansible_play_hosts }}'
  become: yes

- name: List all virtual machines
  virt:
    command: list_vms
  register: libvirt_vms
  become: yes

- name: Delete virtual machines
  virt:
    command: undefine
    name: '{{ hostvars[item].ansible_ssh_host }}'
  when: 'virtual_machines[item] is defined and hostvars[item].ansible_ssh_host in libvirt_vms.list_vms'
  with_items: '{{ ansible_play_hosts }}'
  become: yes

- name: Delete virtual machine disks
  file: path={{ virtual_machines_dir }}/{{ hostvars[item].ansible_ssh_host }}.qcow2 state=absent
  when: 'virtual_machines[item] is defined'
  with_items: '{{ ansible_play_hosts }}'
  become_user: '{{ virtual_machines_user }}'
  become: yes
