- name: List active networks
  virt_net:
    command: list_nets
    state: active
  register: libvirt_active_nets
  become: yes

- name: List all networks
  virt_net:
    command: list_nets
  register: libvirt_nets
  become: yes

- name: Delete networks
  include: network_delete_include.yml
  with_dict: '{{ networks }}'
