- hosts: all
  tasks:
    - import_role:
        name: machine_base
      tags: machine_base

    - import_role:
        name: common_tasks
        tasks_from: configure_common_users.yml

    # Switch to user developer before running the machine_devel role
    - set_fact:
        ansible_ssh_user: developer
      tags: machine_devel

- hosts: all
  tasks:
    - import_role:
        name: machine_devel
      tags: machine_devel
