- hosts: all
  tasks:
    - import_role:
        name: machine_base
      tags: machine_base

    - import_role:
        name: common_tasks
        tasks_from: configure_common_users.yml

- hosts: all
  gather_facts: False
  tasks:
    - name: Add the same host to the inventory but set ansible_ssh_user to developer
      add_host:
        name: '{{ ansible_host }}-developer'
        ansible_ssh_host: '{{ ansible_host }}'
        ansible_ssh_user: developer
        groups: all_developer
      changed_when: False
      tags: machine_devel

- hosts: all_developer
  tasks:
    - import_role:
        name: machine_devel
      tags: machine_devel
