- hosts: localhost
  gather_facts: False
  tasks:
    - import_role:
        name: otlc_common
        tasks_from: retrieve_provisioned_services.yml

    - include_role:
        name: otlc_generic_order
        tasks_from: retrieve_service_attributes.yml
      vars:
        otlc_service_href: '{{ item.href }}'
      loop: '{{ otlc_services_provisioned.json.resources }}'
