- hosts: localhost
  gather_facts: False
  tasks:
    - import_role:
        name: otlc_specific_order
        tasks_from: otlc_ocp4_configuration
      vars:
        otlc_service_desc: '{{ otlc_labs.ocp4_configuration }}'
