- hosts: localhost
  gather_facts: False
  tasks:
    - import_role:
        name: otlc_common
        tasks_from: retrieve_provisioned_services.yml
      vars:
        rhlab_api_host: labs.opentlc.com

    - name: Show provisioned services
      debug:
        var: otlc_services_provisioned.json.resources
