- hosts: all
  gather_facts: no
  vars_prompt:
    - name: aws_key
      prompt: 'Enter aws_key'
      private: no
    - name: aws_secret_key
      prompt: 'Enter aws_secret_key'
      private: yes
    - name: aws_region
      prompt: 'Enter aws_region'
      private: no

  tasks:
    - include_role: name=otlc_openshift
