- hosts: localhost
  gather_facts: False
  tasks:
    - import_role:
        name: otlc_specific_order
        tasks_from: otlc_ossm_lab
      vars:
        otlc_service_desc: '{{ otlc_labs.ossm_lab }}'
