- hosts: all
  gather_facts: yes
  tasks:
    - name: Register with Red Hat Subscription Manager
      redhat_subscription:
        username: '{{ redhat_subscription_user }}'
        password: '{{ redhat_subscription_password }}'
        release: '{{ ansible_distribution_version }}'
        auto_attach: true
        state: present

    - name: Attach Employee SKU
      redhat_subscription:
        username: '{{ redhat_subscription_user }}'
        password: '{{ redhat_subscription_password }}'
        release: '{{ ansible_distribution_version }}'
        pool_ids: 8a85f98460bfb0470160c2ff22f13e47
        state: present

    - name: Enable yum repositories
      ini_file:
        path: /etc/yum.repos.d/redhat.repo
        section: '{{ item }}'
        option: enabled
        value: "1"
      with_items: '{{ (enable_repos | default("[]") | from_yaml )}}'
