- name: ansible-modules-hashivault
  src: https://github.com/TerryHowe/ansible-modules-hashivault.git
  version: 4.2.3
  # requires rpm package python3-hvac

- name: devnullcake.redhat-subscription
  src: https://github.com/noseka1/ansible-role-redhat-subscription.git
  version: master

- name: mprahl.lets-encrypt-route-53
  src: https://github.com/mprahl/ansible-role-lets-encrypt-route-53.git
  version: v4.6.1
  # requires EPEL enabled
