# Run this playbook using:
# ansible-playbook -i inventory/rhev_lab.ini -e ansible_python_interpreter=/usr/bin/python2 rhev_lab.yml
- hosts: rhvh.lab.example.com
  tasks:
    - name: Red Hat subscription
      import_role:
        name: devnullcake.redhat-subscription
      vars:
        redhat_subscription_pool_regex: '{{ redhat_subscription_pool_id }}'
        redhat_subscription_enable_repos:
          - rhel-7-server-rhvh-4-rpms

    - import_role:
        name: rhev_lab
