# Run this playbook using:
# ansible-playbook -i inventory/localhost.ini -e ansible_python_interpreter=/usr/bin/python2 rhv_lab_network.yml
- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - import_role:
        name: rhv_lab
        tasks_from: add_network.yml
