apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-volume-{{ item }}
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
    - ReadOnlyMany
    - ReadWriteOnce
  nfs:
    path: /nfs-backing-volume-{{ item }}
    server: {{ rook_nfs_service.resources.0.spec.clusterIP }}
  persistentVolumeReclaimPolicy: Recycle
