apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-backing-volume-{{ item }}
  namespace: rook-nfs
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-backing-volume
