apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-backing-volume-{{ item }}
  namespace: rook-nfs
spec:
  storageClassName: nfs-backing-volume
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: {{ volume_path }}/{{ item }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
              - {{ volume_node }}
  claimRef:
    name: nfs-backing-volume-{{ item }}
    namespace: rook-nfs
