apiVersion: nfs.rook.io/v1alpha1
kind: NFSServer
metadata:
  name: rook-nfs
  namespace: rook-nfs
spec:
  replicas: 1
  exports:
{% for item in range(1, volume_count + 1) %}
  - name: volume-{{ item }}
    server:
      accessMode: ReadWrite
      squash: none
    persistentVolumeClaim:
      claimName: nfs-backing-volume-{{ item }}
{% endfor %}
