- name: Delete CIS compliance scan
  command: oc delete --kustomize {{ compliance_kustomizations.cis }}

- import_role:
    name: openshift_common
    tasks_from: delete_kubernetes_objects.yml
  vars:
    delete_kubernetes_objects:
      - api_version: compliance.openshift.io/v1alpha1
        kind: ProfileBundle

- name: Delete Compliance operator
  command: oc delete --kustomize {{ compliance_kustomizations.operator }}
