apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: {{ gitops_instance_name }}
  namespace: {{ gitops_instance_namespace }}
spec:
  rbac:
    defaultPolicy: 'role:readonly'
    policy: |
      g, cluster-admins, role:admin
    scopes: '[groups]'
