- import_tasks: order_service.yml
  when: service_id is not defined

- set_fact:
    otlc_service_id: '{{ service_id }}'
  when: service_id is defined

- import_role:
    name: otlc_common
    tasks_from: retrieve_provisioned_service.yml

- import_tasks: retrieve_service_attributes.yml

- import_tasks: check_service_health.yml

- import_tasks: extend_service.yml
  when: service_id is not defined
