all:
  children:
    ungrouped:
      hosts:
        container-1:
          remote_addr: container-1
          remote_user: root
        container-2:
          remote_addr: container-2
          remote_user: root
        container-3:
          remote_addr: container-3
          remote_user: root
        container-4:
          remote_addr: container-4
          remote_user: root
        container-5:
          remote_addr: container-5
          remote_user: root
        container-6:
          remote_addr: container-6
          remote_user: root
        container-7:
          remote_addr: container-7
          remote_user: root
        container-8:
          remote_addr: container-8
          remote_user: root
        container-9:
          remote_addr: container-9
          remote_user: root
