- name: Install AWS CLI
  script: install_aws_cli.sh
  args:
    chdir: /root
    creates: /usr/bin/aws
  become: true

- name: Download OpenShift installer
  script: download_installer.sh
  args:
    chdir: /root
    creates: /usr/bin/openshift-install
  become: true

- name: Download oc CLI tool
  script: download_oc.sh
  args:
    chdir: /root
    creates: /usr/bin/oc
  become: true

- name: Set up bash completion
  script: bash_completion.sh
  args:
    chdir: /root
    creates: /etc/bash_completion.d/openshift
  become: true

- name: Configure AWS CLI
  script: configure_aws_cli.sh
  args:
    creates: .aws/credentials
  environment:
    AWSKEY: '{{ otlc_service_info.aws_access_key_id }}'
    AWSSECRETKEY: '{{ otlc_service_info.aws_secret_access_key }}'
    REGION: '{{ aws_region }}'

- name: Create an SSH keypair to be used for your OpenShift environment
  shell: ssh-keygen -f ~/.ssh/cluster-key -N ''
  args:
    creates: .ssh/cluster-key

- name: Retrieve SSH public key
  shell: cat ~/.ssh/cluster-key.pub
  changed_when: False
  register: ssh_public_key

- name: Create cluster configuration directory
  file: path=cluster-{{ otlc_service_info.guid }} state=directory

- name: Create install-config.yaml
  template: src=install-config.yaml dest=cluster-{{ otlc_service_info.guid }}

- name: Create a hard-link to keep install-config.yaml file around after deletion
  file:
    src: cluster-{{ otlc_service_info.guid }}/install-config.yaml
    dest: cluster-{{ otlc_service_info.guid }}/install-config.link.yaml
    state: hard

- name: Installing the cluster, this will take a while.
  command: openshift-install create cluster --dir=cluster-{{ otlc_service_info.guid }} --log-level=debug
