- name: Add KUBECONFIG environment variable to .bashrc
  lineinfile:
    dest: .bashrc
    regexp: KUBECONFIG=
    line:  export KUBECONFIG={{ cluster_config_dir }}/auth/kubeconfig
    state: present

- name: Create htpassword file holding additional OpenShift users
  htpasswd:
    path: '{{ cluster_config_dir }}/htpasswd'
    name: '{{ item.name }}'
    password: '{{ item.password }}'
  with_items:
    - { name: admin,     password: '{{ generic_user_password }}' }
    - { name: developer, password: '{{ generic_user_password }}' }

- name: Retrieve htpasswd file
  shell: cat {{ cluster_config_dir }}/htpasswd
  changed_when: False
  register: htpasswd

- name: Create htpasswd secret
  k8s:
    definition: "{{ lookup('template', 'htpasswd-secret.yml') }}"

- name: Configure authentication using htpasswd
  k8s:
    definition: "{{ lookup('template', 'cluster-oauth.yml') }}"

- name: Grant admin user the cluster-admin role
  k8s:
    definition: "{{ lookup('template', 'cluster-admin-0-clusterrolebinding.yml') }}"
