- name: Create the certificate secrets
  include_tasks: postinstall_certs_secret.yml
  with_items:
    - { secret_name: api-cert,      namespace: openshift-config,  common_name:    'api.cluster-{{ otlc_service_info.guid }}.{{ otlc_service_info.top_level_domain }}' }
    - { secret_name: wildcard-cert, namespace: openshift-ingress, common_name: '*.apps.cluster-{{ otlc_service_info.guid }}.{{ otlc_service_info.top_level_domain }}' }

- name: Configure API server certificate
  k8s:
    definition:
      apiVersion: config.openshift.io/v1
      kind: APIServer
      metadata:
        name: cluster
      spec:
        servingCerts:
            namedCertificates:
              - names:
                  - 'api.cluster-{{ otlc_service_info.guid }}.{{ otlc_service_info.top_level_domain }}'
                servingCertificate:
                  name: api-cert

- name: Configure wildcard apps certificate
  k8s:
    definition:
      apiVersion: operator.openshift.io/v1
      kind: IngressController
      metadata:
        name: default
        namespace: openshift-ingress-operator
      spec:
        defaultCertificate:
          name: wildcard-cert
