- name: Create cluster configuration directory
  file: path={{ cluster_config_dir }} state=directory

- name: Copy the OpenShift installer download script
  template:
    src: download_installer.sh
    dest: '{{ cluster_config_dir }}'
    mode: '0755'
  become: true

- name: Download OpenShift installer {{ openshift_version }}
  command: '{{ cluster_config_dir }}/download_installer.sh'
  args:
    chdir: /root
    creates: /usr/bin/openshift-install
  become: true

- name: Copy the OpenShift CLI download script
  template:
    src: download_oc.sh
    dest: '{{ cluster_config_dir }}'
    mode: '0755'
  become: true

- name: Download oc CLI tool {{ openshift_version }}
  command: '{{ cluster_config_dir }}/download_oc.sh'
  args:
    chdir: /root
    creates: /usr/bin/oc
  become: true

- name: Set up bash completion
  script: bash_completion.sh
  args:
    chdir: /root
    creates: /etc/bash_completion.d/openshift
  become: true

- name: Install AWS CLI
  script: install_aws_cli.sh
  args:
    chdir: /root
    creates: /usr/bin/aws
  become: true

- name: Configure AWS CLI
  script: configure_aws_cli.sh
  args:
    creates: .aws/credentials
  environment:
    AWSKEY: '{{ otlc_service_info.aws_access_key_id }}'
    AWSSECRETKEY: '{{ otlc_service_info.aws_secret_access_key }}'
    REGION: '{{ aws_region }}'

- name: Create an SSH keypair to be used for your OpenShift environment
  shell: ssh-keygen -f ~/.ssh/cluster-key -N ''
  args:
    creates: .ssh/cluster-key
