- name: Install AWS CLI
  script: install_aws_cli.sh
  args:
    chdir: /root
    creates: /usr/bin/aws
  become: true

- name: Download OpenShift installer
  script: download_installer.sh
  args:
    chdir: /root
    creates: /usr/bin/openshift-install
  become: true

- name: Download oc CLI tool
  script: download_oc.sh
  args:
    chdir: /root
    creates: /usr/bin/oc
  become: true

- name: Set up bash completion
  script: bash_completion.sh
  args:
    chdir: /root
    creates: /etc/bash_completion.d/openshift
  become: true

- name: Configure AWS CLI
  script: configure_aws_cli.sh
  args:
    creates: .aws/credentials
  environment:
    AWSKEY: '{{ otlc_service_info.aws_access_key_id }}'
    AWSSECRETKEY: '{{ otlc_service_info.aws_secret_access_key }}'
    REGION: '{{ aws_region }}'

- name: Create an SSH keypair to be used for your OpenShift environment
  shell: ssh-keygen -f ~/.ssh/cluster-key -N ''
  args:
    creates: .ssh/cluster-key
