- name: Set cluster_id
  set_fact:
    ocs_cluster_id: '{{ infrastructure.resources.0.status.infrastructureName }}'

- name: Set AWS region
  set_fact:
    ocs_aws_region: '{{ infrastructure.resources.0.status.platformStatus.aws.region }}'

- name: Set AWS ami id
  set_fact:
    ocs_ami_id: '{{ aws_rhcos_ami[ocs_aws_region] }}'

- name: Add machine sets to the cluster
  k8s:
    definition: '{{ lookup("template", "ocs-machineset.yml") }}'
  with_items: '{{ ocs_aws.availability_zones }}'

- name: Waiting since {{ lookup("pipe", "date +%r") }} for machines to come up
  k8s_info:
    api_version: machine.openshift.io/v1beta1
    kind: MachineSet
    namespace: openshift-machine-api
    name: '{{ ocs_cluster_id }}-ocs-{{ ocs_aws_region }}{{ item }}'
  register: ocs_machineset
  until:
    - ocs_machineset.resources.0.status is defined
    - ocs_machineset.resources.0.status.readyReplicas is defined
    - ocs_machineset.resources.0.status.readyReplicas == (ocs_aws.nodes_per_zone | int)
  retries: 60
  delay: 10
  with_items: '{{ ocs_aws.availability_zones }}'

- name: Wait for the nodes to join the cluster
  import_role:
    name: openshift_common
    tasks_from: wait_for_nodes.yml
  vars:
    expand_node_selector: '{{ ocs_node_label }}'
    expand_nodes_total: '{{ (ocs_aws.availability_zones | length) * ocs_aws.nodes_per_zone }}'
