- name: Obtain infrastructure info
  k8s_info:
    api_version: config.openshift.io/v1
    kind: Infrastructure
    name: cluster
  register: infrastructure

- name: Add nodes to the OpenShift cluster
  include_tasks: add_nodes.yml
  when: infrastructure.resources.0.status.platformStatus.type == 'AWS'

- name: Get labeled OCS nodes
  k8s_info:
    api_version: v1
    kind: Node
    label_selectors:
      - '{{ ocs_node_label }}'
  register: ocs_nodes_result

- fail:
    msg: "Need at least 3 OCS nodes. You can label cluster nodes using: 'oc label nodes <node> {{ ocs_node_label }}='"
  when: (ocs_nodes_result.resources | list | length) < 3

- name: Install OpenShift Container Storage
  import_tasks: deploy_ocs.yml
