- name: Delete {{ rhacm_managed_cluster.cluster_name }} managed cluster
  k8s:
    definition: "{{ lookup('template', '{{ item }}') }}"
    state: absent
    wait: True
  loop:
    - cluster-managedcluster.yaml
    - cluster-ns.yml
