- name: Check if kind cluster has already been deployed
  command: kubectl cluster-info --context kind-kind
  ignore_errors: True
  register: cluster_info_result
  become: True

- name: Delete kind cluster
  command: /usr/local/bin/kind delete cluster
  environment:
    KIND_EXPERIMENTAL_PROVIDER: podman
  register: delete_kind_result
  when: cluster_info_result is success
  become: True

- debug:
    var: delete_kind_result.stderr_lines
  when: delete_kind_result is changed
