- import_role:
    name: machine_base
  tags: machine_base

- name: Install kubectl and podman
  yum:
    name:
      - openshift-clients
      - podman
    enablerepo: rhocp-4.9-for-rhel-8-x86_64-rpms
  become: True

- name: Download kind {{ kind_version }} binary
  get_url:
    url: '{{ kind_url }}'
    dest: /usr/local/bin/kind
    mode: '0755'
  become: True

- name: Check if kind cluster has already been deployed
  command: kubectl cluster-info --context kind-kind
  ignore_errors: True
  register: cluster_info_result
  become: True

- name: Deploy kind cluster
  command: /usr/local/bin/kind create cluster
  environment:
    KIND_EXPERIMENTAL_PROVIDER: podman
  register: deploy_kind_result
  when: cluster_info_result is failed
  become: True

- debug:
    var: deploy_kind_result.stderr_lines
  when: deploy_kind_result is changed

- name: Retrieve cluster info
  shell: kubectl cluster-info --context kind-kind | sed -r "s/\x1B\[([0-9]{1,3}(;[0-9]{1,2})?)?[mGK]//g"
  register: cluster_info_result
  become: True

- debug:
    var: cluster_info_result.stdout_lines
