- name: Obtain existing Kubernetes objects of kind {{ delete_objects_kind }}
  k8s_info:
    api_version: '{{ delete_objects_apiver }}'
    kind: '{{ delete_objects_kind }}'
  register: existing_objects

- name: Delete {{ existing_objects.resources | length }} Kubernetes objects of kind {{ delete_objects_kind }}
  k8s:
    api_version: '{{ delete_objects_apiver }}'
    kind: '{{ delete_objects_kind }}'
    name: '{{ item.metadata.name }}'
    namespace: '{{ item.metadata.namespace | default(omit) }}'
    state: absent
  loop: '{{ existing_objects.resources }}'

- name: Waiting until all objects of kind {{ delete_objects_kind }} have been deleted
  k8s_info:
    api_version: '{{ delete_objects_apiver }}'
    kind: '{{ delete_objects_kind }}'
  register: remaining_objects
  until: remaining_objects.resources | length == 0
  retries: 30
  delay: 10
