- name: Wait for {{ stable_cluster_delay }} seconds
  wait_for:
    timeout: '{{ stable_cluster_delay }}'

- name: Waiting since {{ lookup("pipe", "date +%r") }} for Kubernetes APIs to become available
  command: oc version
  ignore_errors: True
  changed_when: False
  register: oc_version_result
  until:
    - oc_version_result is not failed
  retries: 30
  delay: 10

- name: Show cluster info
  debug:
    var: oc_version_result.stdout_lines

- name: Waiting since {{ lookup("pipe", "date +%r") }} for OpenShift APIs to become available
  command: oc api-resources
  ignore_errors: True
  changed_when: False
  register: api_resources_result
  until:
    - api_resources_result is not failed
  retries: 30
  delay: 10

- name: Reset retry count and job complete
  set_fact:
    stable_cluster_retry_count: -1
    stable_cluster_job_complete: False

- name: Waiting since {{ lookup("pipe", "date +%r") }} for the cluster operators to stabilize
  include_tasks: wait_for_stable_cluster_subtasks.yml
