- name: Wait for {{ stable_cluster_delay }} seconds
  wait_for:
    timeout: '{{ stable_cluster_delay }}'

- name: Waiting since {{ lookup("pipe", "date +%r") }} for the cluster to stabilize
  include_tasks: wait_for_stable_cluster_subtasks.yml

- name: Waiting since {{ lookup("pipe", "date +%r") }} for pods to recover
  k8s_info:
    api_version: v1
    kind: Pod
    field_selectors:
      - metadata.namespace!=openshift-marketplace
      - status.phase!=Running
      - status.phase!=Succeeded
  register: recovering_pods
  until:
    - recovering_pods.resources | length == 0
  retries: 60
  delay: 10

- name: Waiting since {{ lookup("pipe", "date +%r") }} for OpenShift APIs to become available
  k8s_info:
    api_version: apiregistration.k8s.io/v1
    kind: APIService
    name: '{{ apiservice_item }}'
  loop:
    - v1.oauth.openshift.io
    - v1.packages.operators.coreos.com
    - v1.project.openshift.io
    - v1.user.openshift.io
  loop_control:
    loop_var: apiservice_item
  register: openshift_api_result
  until:
    - openshift_api_result.resources is defined
    - openshift_api_result.resources | length > 0
    - openshift_api_result.resources.0.status is defined
    - openshift_api_result.resources.0.status.conditions | selectattr('type', 'equalto', 'Available') | list | length > 0
    - (openshift_api_result.resources.0.status.conditions | selectattr('type', 'equalto', 'Available') | first).status == 'True'
  retries: 60
  delay: 10
