- name: Enable generic secret kv store
  hashivault_secret_engine:
    name: kv
    backend: generic
  environment:
    VAULT_ADDR: '{{ vault_addr }}'
    VAULT_SKIP_VERIFY: '{{ vault_skip_verify }}'
    VAULT_TOKEN: '{{ vault_token }}'

- name: Insert secret into vault
  hashivault_write:
    secret: /kv/data/mysecret
    data:
      generic_user_password: '{{ generic_user_password }}'
      redhat_quay_pull_secret: '{{ redhat_quay_pull_secret }}'
      testkey: testvalue
  environment:
    VAULT_ADDR: '{{ vault_addr }}'
    VAULT_SKIP_VERIFY: '{{ vault_skip_verify }}'
    VAULT_TOKEN: '{{ vault_token }}'
