- name: Apply kustomization
  command: oc apply --kustomize {{ item }}
  with_items: '{{ vault_kustomizations }}'

- name: Obtain vault route
  k8s_info:
    api_version: route.openshift.io/v1
    kind: Route
    name: vault
    namespace: '{{ vault_namespace }}'
  register: vault_route

- name: Set vault URL
  set_fact:
    vault_addr: 'https://{{ vault_route.resources.0.spec.host }}'

- name: Waiting since {{ lookup("pipe", "date +%r") }} for vault to come up
  uri:
    url: '{{ vault_addr }}/v1/sys/health'
    method: GET
    validate_certs: False
    status_code: [ 200, 501 ]
  register: vault_health
  until: vault_health.status in [ 200, 501 ]
  retries: 60
  delay: 10
