- name: Obtain vault route
  k8s_info:
    api_version: route.openshift.io/v1
    kind: Route
    name: vault
    namespace: '{{ vault_namespace }}'
  register: vault_route

- set_fact:
    vault_addr: 'https://{{ vault_route.resources.0.spec.host }}'

- name: Check whether vault has already been initialized
  hashivault_init:
    secret_shares: 1
    secret_threshold: 1
  register: vault_init
  environment:
    VAULT_ADDR: '{{ vault_addr }}'
    VAULT_SKIP_VERIFY: '{{ vault_skip_verify }}'

- name: Initialize vault
  import_tasks: init.yml
  when: vault_init["keys"][0] is defined

- name: Retrieve an admin token
  import_tasks: admin_token.yml

- name: Configure the Kubernetes auth method
  import_tasks: kube_auth.yml

- name: Enable audit logs
  import_tasks: enable_audit.yml
