- include: retrieve_service.yml

- set_fact:
    send_order: '{{  otlc_service | length  == 0 }}'

- block:
    - include: order_service.yml
    - include: retrieve_service.yml
    - include: extend_service.yml
  when: send_order
