- name: Retrieve attributes of service {{ otlc_service.0.href }}
  uri:
    url: '{{ otlc_service.0.href }}?expand=custom_attributes'
    user: '{{ otlc_username }}'
    password: '{{ otlc_password }}'
    method: GET
    status_code: 200
  register: otlc_service_attributes

- set_fact:
    otlc_service_info:
      guid: '{{ (otlc_service_attributes.json.custom_attributes | selectattr("name", "equalto", "GUID") | first).value }}'
      env0: '{{ (otlc_service_attributes.json.custom_attributes | selectattr("name", "equalto", "Environment Info 0") | first).value }}'
      env1: '{{ (otlc_service_attributes.json.custom_attributes | selectattr("name", "equalto", "Environment Info 1") | first).value }}'
      env2: '{{ (otlc_service_attributes.json.custom_attributes | selectattr("name", "equalto", "Environment Info 2") | first).value }}'
      env3: '{{ (otlc_service_attributes.json.custom_attributes | selectattr("name", "equalto", "Environment Info 3") | first).value }}'
      env4: '{{ (otlc_service_attributes.json.custom_attributes | selectattr("name", "equalto", "Environment Info 4") | first).value }}'
      env5: '{{ (otlc_service_attributes.json.custom_attributes | selectattr("name", "equalto", "Environment Info 5") | first).value }}'
      env6: '{{ (otlc_service_attributes.json.custom_attributes | selectattr("name", "equalto", "Environment Info 6") | first).value }}'

- debug:
    var: otlc_service_info
