kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: thin-csi
{% if not default_storage_class_exists %}
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
{% endif %}
allowVolumeExpansion: true
provisioner: csi.vsphere.vmware.com
