apiVersion: v1
kind: Secret
metadata:
  name: vsphere-config-secret
  namespace: vmware-system-csi
stringData:
  csi-vsphere.conf: |
    [Global]
    cluster-id = mycluster
    cluster-distribution = Openshift
    # ca-file = <ca file path> # optional, use with insecure-flag set to false
    # thumbprint = "<cert thumbprint>" # optional, use with insecure-flag set to false without providing ca-file

    [VirtualCenter "{{ vsphere_lab.vcenter_hostname }}"]
    insecure-flag = "true"
    user = "{{ vsphere_lab.vcenter_username }}"
    password = "{{ vsphere_lab.vcenter_password }}"
    port = "443"
    datacenters = "{{ vsphere_lab.datacenter_name }}"
