apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vsphere-scc
  namespace: vmware-system-csi
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: vsphere-scc
subjects:
- kind: ServiceAccount
  name: vsphere-csi-node
