- name: Obtain Minio API route
  import_role:
    name: openshift_minio
    tasks_from: get_minio_api_route.yml
  vars:
    minio_namespace: '{{ rhacm_minio_namespace }}'
  when: rhacm_observability_use_existing_s3 == "false"

- import_tasks: retrieve_pull_secret.yml

- name: Delete Observability component
  import_role:
    name: openshift_common
    tasks_from: kustomize.yml
  vars:
    kustomize_name: rhacm_observability
    kustomize_files:
      - kustomization.yaml
      - pull-secret-secret.yaml
      - thanos-object-storage-secret.yaml
    kustomize_op: delete
  when: rhacm_observability_use_existing_s3 == "false"

- name: Delete Observability component
  import_role:
    name: openshift_common
    tasks_from: kustomize.yml
  vars:
    kustomize_name: rhacm_observability
    kustomize_files:
      - kustomization.yaml
      - pull-secret-secret.yaml
      - thanos-object-storage-secret-existing-s3.yaml
    kustomize_op: delete
  when: rhacm_observability_use_existing_s3 == "true"

- import_role:
    name: openshift_minio
    tasks_from: delete.yml
  vars:
    minio_namespace: '{{ rhacm_minio_namespace }}'
  when: rhacm_observability_use_existing_s3 == "false"
