- name: Deploy minio
  import_role:
    name: openshift_minio
    tasks_from: deploy.yml
  vars:
    minio_namespace: '{{ rhacm_minio_namespace }}'

- name: Retrieve OpenShift pull secret
  k8s_info:
    api_version: v1
    kind: Secret
    name: pull-secret
    namespace: openshift-config
  register: openshift_pull_secret

- name: Deploy Observability component
  import_role:
    name: openshift_common
    tasks_from: kustomize.yml
  vars:
    kustomize_name: rhacm_observability
    kustomize_files:
      - kustomization.yaml
      - pull-secret-secret.yaml
      - thanos-object-storage-secret.yaml
    kustomize_op: apply
