# To obtain the CRDs for the cluster backup operator:
# git clone https://github.com/open-cluster-management/cluster-backup-operator
# cd cluster-backup-operator
# make manifests
# kustomize build config/crd | csplit - '/^apiVersion: .*/' '{*}'
#
- name: Deploy cluster backup operator CRDs
  k8s:
    definition: "{{ lookup('file', item, split_lines='no') }}"
  loop:
    - backupschedules.cluster.open-cluster-management.io-crd.yaml
    - restores.cluster.open-cluster-management.io-crd.yaml

- name: Create temporary directory
  tempfile:
    state: directory
    suffix: -{{ rhacm_cluster_backup_operator_name }}
  register: tmpdir

- debug:
    msg: Created temporary directory {{ tmpdir.path }}

- name: Git clone stable repo on HEAD
  git:
    repo: '{{ rhacm_cluster_backup_operator_git }}'
    dest: '{{ tmpdir.path }}'

- name: Deploy RHACM cluster backup operator
  community.kubernetes.helm:
    name: '{{  rhacm_cluster_backup_operator_name }}'
    chart_ref: '{{ tmpdir.path }}/stable/cluster-backup-chart'
    release_namespace: '{{ rhacm_cluster_backup_operator_namespace }}'
    wait: True

- name: Delete temporary directory {{ tmpdir.path }}
  file:
    path: '{{ tmpdir.path }}'
    state: absent
