- name: Create temporary directory
  tempfile:
    state: directory
    suffix: -rhacm
  register: tmpdir

- git:
    repo: https://github.com/open-cluster-management/acm-hive-openshift-releases
    dest: '{{ tmpdir.path }}'
    version: main

- replace:
    path: '{{ tmpdir.path }}/subscribe/kustomization.yaml'
    regexp: subscription-fast
    replace: subscription-stable

- name: Subscribe to stable OCP releases
  command: oc apply --kustomize {{ tmpdir.path }}/subscribe

- name: Delete temporary directory {{ tmpdir.path }}
  file:
    path: '{{ tmpdir.path }}'
    state: absent
