- name: Deploy corrected SCC
  k8s:
    definition: "{{ lookup('template', 'rook-nfs-scc.yml') }}"

- name: Deploy Rook NFS operator
  k8s:
    definition: "{{ lookup('url', item, split_lines='no') }}"
  loop:
    - '{{ rook_base_url }}/cluster/examples/kubernetes/nfs/crds.yaml'
    - '{{ rook_base_url }}/cluster/examples/kubernetes/nfs/rbac.yaml'
    - '{{ rook_base_url }}/cluster/examples/kubernetes/nfs/operator.yaml'

- name: Create directory on the {{ volume_node }} node for the volume
  command: >
    oc debug node/{{ volume_node }} --namespace default --
      /bin/bash -c '
        set -e
        dir=/host/{{ volume_path }};
        mkdir -p $dir;
        chown 0.0 $dir;
        chmod 775 $dir;
        chcon -R -t container_file_t -l s0 $dir;
      '

- name: Create backing PV and PVC
  k8s:
    definition: "{{ lookup('template', item) }}"
  loop:
     - nfs-backing-volume-pv.yml
     - nfs-backing-volume-pvc.yml

- name: Deploy Rook NFS server
  k8s:
    definition: "{{ lookup('template', item) }}"
  loop:
    - rook-nfs-nfsserver.yml

- name: Wait until Rook NFS service shows up
  k8s_info:
    api_version: v1
    kind: Service
    name: rook-nfs
    namespace: rook-nfs
  register: rook_nfs_service
  until: rook_nfs_service.resources | length > 0
  retries: 60
  delay: 10
