apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: topolvm-scc
  namespace: {{ topolvm_instance_namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: topolvm-scc
subjects:
- kind: ServiceAccount
  name: topolvm-preparevg
- kind: ServiceAccount
  name: topolvm-discover
- kind: ServiceAccount
  name: topolvm-node
