apiVersion: topolvm.cybozu.com/v2
kind: TopolvmCluster
metadata:
  name: {{ topolvm_instance_name }}
  namespace: {{ topolvm_instance_namespace }}
spec:
  topolvmVersion: alaudapublic/topolvm:2.0.0
  storage:
    useAllNodes: true
    useAllDevices: false
    useLoop: true
    volumeGroupName: loop1-vg
    className: topolvm-hdd
    devices:
      - # Loop device name
        name: loop1
        type: loop
        # Operator will create loop device (true)
        auto: true
        # Directory where the loop device backing file will be created
        path: /var/local
        # Device size in GiB
        size: 2048
