- name: Check if default storage class exists
  import_role:
    name: openshift_common
    tasks_from: check_default_storage_class_exists.yml

- name: Delete topolvm storage class
  k8s:
    definition: "{{ lookup('template', '{{ item }}') }}"
    state: absent
  loop:
    - topolvm-sc.yaml

- name: Delete TopoLVM instance
  k8s:
    definition: "{{ lookup('template', '{{ item }}') }}"
    state: absent
  loop:
    - topolvm-scc-role.yaml
    - topolvm-scc-rolebinding.yaml
    - global-info-cm.yaml
    - topolvm-topolvmcluster.yaml

- name: Delete TopoLVM operator
  k8s:
    definition: "{{ lookup('template', '{{ item }}') }}"
    state: absent
  loop:
    - topolvm-operator-sub.yaml
