apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: {{ oadp_subscription_name }}
  namespace: {{ oadp_subscription_namespace }}
spec:
  channel: beta
  installPlanApproval: Automatic
  name: oadp-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
