apiVersion: oadp.openshift.io/v1alpha1
kind: Velero
metadata:
  name: velero
spec:
  backupStorageLocations:
    - provider: aws
      objectStorage:
        bucket: mybucket-1
        prefix: velero
      config:
        s3Url: https://{{ minio_route.resources.0.spec.host }}
        s3ForcePathStyle: "true"
        region: minio
        profile: default
        insecureSkipTLSVerify: "true"
      accessMode: ReadWrite
      credential:
        name: cloud-credentials
        key: data
      default: True
