ocs_aws:
  instance_type: m4.4xlarge
  availability_zones: [ a, b, c ]
  nodes_per_zone: 1

ocs_kustomizations:
  operator:         github.com/noseka1/ocs-kustomization/ocs-operator/base?ref=myauto
  instance_aws:     github.com/noseka1/ocs-kustomization/ocs-instance/overlays/aws?ref=myauto
  instance_openebs: github.com/noseka1/ocs-kustomization/ocs-instance/overlays/openebs?ref=myauto
  tools:            github.com/noseka1/ocs-kustomization/rook-ceph-tools/base?ref=myauto
ocs_subscription_namespace: openshift-storage
ocs_subscription_name: ocs-operator
ocs_instance_namespace: openshift-storage
ocs_instance_name: ocs-storagecluster
