apiVersion: v1
data:
  superuser-email: '{{ "quay@redhat.com" | b64encode }}'
  superuser-password: '{{ generic_user_password | b64encode }}'
  superuser-username: '{{ "quay" | b64encode }}'
kind: Secret
metadata:
  name: superuser
  namespace: '{{ quay_namespace }}'
type: Opaque
