apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: {{ jaeger_instance_name }}
  namespace: {{ jaeger_instance_namespace }}
spec:
  allInOne:
    options:
      log-level: info
  strategy: allInOne
