apiVersion: config.openshift.io/v1
kind: APIServer
metadata:
  name: cluster
spec:
  servingCerts:
    namedCertificates:
    - names:
      - {{ osh_lab_api_domain }}
      servingCertificate:
        name: api-cert
