- name: Check if EPEL repo is already configured
  stat:
    path: '{{ epel_repofile_path }}'
  register: epel_repofile_result

- name: Install EPEL repo
  yum:
    name: '{{ epel_repo_url }}'
  register: result
  when: not epel_repofile_result.stat.exists
  become: True

- name: Import EPEL GPG key
  rpm_key:
    key: '{{ epel_repo_gpg_key_url }}'
  when: not epel_repofile_result.stat.exists
  become: True
