apiVersion: v1
data:
  access-key: {{ external_secrets_secretstore_aws_access_key | b64encode }}
  secret-access-key: {{ external_secrets_secretstore_aws_secret_key | b64encode }}
kind: Secret
metadata:
  name: awssm-secret
  namespace: {{ external_secrets_instance_namespace }}
type: Opaque
