apiVersion: external-secrets.io/v1alpha1
kind: SecretStore
metadata:
  name: secretstore-aws-sm
  namespace: {{ external_secrets_instance_namespace }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ external_secrets_secretstore_aws_region }}
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: awssm-secret
            key: access-key
          secretAccessKeySecretRef:
            name: awssm-secret
            key: secret-access-key
