apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: aws-external-secret-test
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: secretstore-sample
    kind: SecretStore
  target:
    name: secret-to-be-created
    creationPolicy: Owner
  data:
  - secretKey: firstname
    remoteRef:
      key: mysecret-test
      property: name.first
