apiVersion: v1
kind: Secret
metadata:
  name: {{ rhacm_managed_cluster.cluster_name }}-pull-secret
  namespace: {{ rhacm_managed_cluster.cluster_name }}
stringData:
  .dockerconfigjson: '{{ redhat_cloud_pull_secret | string }}'
type: kubernetes.io/dockerconfigjson
