apiVersion: v1
kind: Secret
metadata:
  name: {{ rhacm_managed_cluster.cluster_name }}-ssh-private-key
  namespace: {{ rhacm_managed_cluster.cluster_name }}
stringData:
  ssh-privatekey: '{{ generic_ssh_key_pair.private_key }}'
