apiVersion: v1
kind: Secret
metadata:
  name: {{ rhacm_managed_cluster.cluster_name }}-aws-creds
  namespace: {{ rhacm_managed_cluster.cluster_name }}
stringData:
  aws_access_key_id: {{ rhacm_managed_cluster.aws_access_key_id }}
  aws_secret_access_key: {{ rhacm_managed_cluster.aws_secret_access_key }}
