apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: {{ auto_controller_namespace }}

bases:
- {{ aap_kustomizations.auto_controller }}

resources:
- auto-controller-custom-admin-password-secret.yaml

patchesStrategicMerge:
- auto-controller-automationcontroller.yaml
