apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: {{ metallb_subscription_name }}
  namespace: {{ metallb_subscription_namespace }}
spec:
  channel: stable
  installPlanApproval: Automatic
  name: metallb-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
