- name: Install haproxy
  yum: name=haproxy state=present
  become: yes

- name: Configure HAProxy
  template: src=haproxy.cfg dest=/etc/haproxy/haproxy.cfg
  notify: Restart haproxy
  become: yes

- name: Enable ports on firewall
  firewalld:
    port: '{{ item }}/tcp'
    permanent: yes
    immediate: yes
    state: enabled
  with_items:
    - 6443
    - 22623
    - 443
    - 80
    - 1993
  become: yes

- name: Allow HAProxy to listen on ports
  seport:
    ports: 6443, 22623, 1993
    proto: tcp
    setype: http_port_t
    state: present
  become: yes
