- import_role:
    name: openshift_common
    tasks_from: postinstall_certs.yml
  vars:
    openshift_cluster_certs: '{{ osh_lab_certs }}'

- import_role:
    name: openshift_common
    tasks_from: postinstall_users.yml

- import_role:
    name: openshift_common
    tasks_from: postinstall_oauth.yml

- import_role:
    name: openshift_common
    tasks_from: postinstall_image_registry.yml

- import_role:
    name: openshift_common
    tasks_from: postinstall_audit.yml

- import_role:
    name: openshift_common
    tasks_from: postinstall_image_prunning.yml

- import_tasks: postinstall_image_registry.yml

- import_role:
    name: openshift_common
    tasks_from: postinstall_monitoring.yml

- import_role:
    name: openshift_common
    tasks_from: postinstall_alerting.yml
