- name: Check if default storage class exists
  import_role:
    name: openshift_common
    tasks_from: check_default_storage_class_exists.yml

- import_role:
    name: openshift_openebs
    tasks_from: deploy.yml
  when: not default_storage_class_exists

- import_role:
    name: openshift_common
    tasks_from: postinstall_common.yml

- import_role:
    name: openshift_common
    tasks_from: postinstall_cluster_wide_proxy.yml
  vars:
    openshift_cluster_certs: '{{ osh_lab_certs }}'
    openshift_cluster_wide_proxy: '{{ osh_lab_proxy | default(omit) }}'
