- name: Check if default storage class exists
  import_role:
    name: openshift_common
    tasks_from: check_default_storage_class_exists.yml

- import_role:
    name: openshift_openebs
    tasks_from: deploy.yml
  when: not default_storage_class_exists

- import_role:
    name: openshift_common
    tasks_from: postinstall_common.yml
  vars:
    openshift_common_cluster_wide_proxy: '{{ osh_lab_proxy | default(omit) }}'

- import_role:
    name: openshift_common
    tasks_from: postinstall_endpoint_certs.yml
  vars:
    openshift_common_endpoint_certs: '{{ osh_lab_certs | default(omit) }}'
