apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: grafana

bases:
- {{ grafana_kustomizations.instance }}

patchesStrategicMerge:
- prometheus-grafanadashboard.yaml
- prometheus-grafanadatasource.yaml
