external_secrets_namespace: external-secrets
external_secrets_name: external-secrets

# Pin the Helm Chart version
#external_secrets_chart_version: 0.4.1

vault_name: vault
vault_namespace: vault
openshift_external_secrets_vault_ca_bundle: ''
