metallb_address_pool: 192.168.150.10-192.168.150.19

metallb_subscription_name: metallb-operator
metallb_subscription_namespace: metallb-system

metallb_instance_name: metallb
metallb_instance_namespace: metallb-system
