apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: central
  namespace: {{ rhacs_central_namespace }}
spec:
  port:
    targetPort: https
  tls:
    termination: passthrough
  to:
    kind: Service
    name: central
