- name: Reset dnf module virt before switching it to virt:av
  command: dnf module reset virt --assumeyes
  become: True

- name: Enable dnf module virt:av
  command: dnf module enable virt:av --assumeyes
  become: True

- name: Install rpms
  yum:
    name:
      - firewalld
      - rhvm-appliance
      - ovirt-hosted-engine-setup
    state: present
  become: True

- name: Ensure vdsm user is in the sanlock group (workaround for https://access.redhat.com/solutions/632983)
  user:
    name: vdsm
    groups: sanlock
    append: True
  become: True

- name: Firewalld is required to be enabled and active in order to correctly deploy hosted-engine
  service:
    name: firewalld
    state: started
    enabled: True

- name:
  template:
    src: '{{ item }}'
    dest: '{{ ansible_env["HOME"] }}/{{ item }}'
  loop:
    - hosted-engine-deploy-answers-file.conf

- debug:
    msg: Continue the installation using command 'ssh root@rhvh.lab.example.com hosted-engine --deploy --config-append=/root/hosted-engine-deploy-answers-file.conf'
