- import_role:
    name: openshift_common
    tasks_from: delete_kubernetes_objects.yml
  vars:
    delete_kubernetes_objects:
      - api_version: v1alpha1
        kind: KeycloakRealm
      - api_version: v1alpha1
        kind: KeycloakClient

- name: Delete RHSSO instance
  command: oc delete --kustomize {{ rhsso_kustomizations.instance }}

- name: Delete RHSSO operator
  command: oc delete --kustomize {{ rhsso_kustomizations.operator }}
