apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ openebs_name }}-scc
  namespace: {{ openebs_namespace }}
rules:
- apiGroups:
  - security.openshift.io
  resourceNames:
  - privileged
  resources:
  - securitycontextconstraints
  verbs:
  - use
