apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
{% if not default_storage_class_exists %}
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
{% endif %}
  name: openebs-lvm
parameters:
  storage: lvm
  volgroup: loop0-vg
  thinProvision: 'yes'
allowVolumeExpansion: true
provisioner: local.csi.openebs.io
volumeBindingMode: WaitForFirstConsumer
