apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ openebs_name }}-scc
  namespace: {{ openebs_namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ openebs_name }}-scc
subjects:
- kind: ServiceAccount
  name: openebs
- kind: ServiceAccount
  name: openebs-lvm-node-sa
