apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: openebs-lvm
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
parameters:
  storage: lvm
  volgroup: loop0-vg
provisioner: local.csi.openebs.io
