apiVersion: v1
kind: Secret
metadata:
  name: argocd-secret
stringData:
  admin.password: '{{ generic_user_password | string | password_hash("bcrypt") }}'
  admin.passwordMtime: '{{ ansible_date_time.iso8601 }}'
