apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: {{ argocd_namespace }}
bases:
  - {{ argocd_resource }}
patchesStrategicMerge:
  - argocd-secret-secret.yaml
resources:
  - argocd-namespace.yaml
  - argocd-server-route.yaml
