- import_tasks: get_infrastructure.yml

- name: Delete Velero instance
  import_role:
    name: openshift_common
    tasks_from: kustomize.yml
  vars:
    kustomize_name: oadp
    kustomize_files:
      - kustomization.yaml
      - cloud-credentials-secret.yaml
    kustomize_op: delete

- name: Delete OADP operator
  command: oc delete --kustomize {{ oadp_kustomizations.operator }}
