- name: Deploy OADP operator
  command: oc apply --kustomize {{ oadp_kustomizations.operator }}

- name: Wait for OADP operator to deploy
  import_role:
    name: openshift_common
    tasks_from: wait_for_operator.yml
  vars:
    subscription_name: '{{ oadp_subscription_name }}'
    subscription_namespace: '{{ oadp_subscription_namespace }}'

- import_tasks: get_infrastructure.yml

- name: Create temporary kustomize directory
  tempfile:
    state: directory
    suffix: -velero-kustomize
  register: tmpdir

- debug:
    msg: Created temporary directory {{ tmpdir.path }}

- name: Copy kustomization config to {{ tmpdir.path }}
  template:
    src: '{{ item }}'
    dest: '{{ tmpdir.path }}'
  with_items:
    - kustomization.yaml
    - cloud-credentials-secret.yaml

- name: Deploy Velero instance
  command: oc apply --kustomize {{ tmpdir.path }}

- name: Delete temporary kustomize directory {{ tmpdir.path }}
  file:
    path: '{{ tmpdir.path }}'
    state: absent
