- name: Deploy RHACS operator
  command: oc apply --kustomize {{ rhacs_kustomizations.operator }}

- name: Wait for RHACS operator to deploy
  import_role:
    name: openshift_common
    tasks_from: wait_for_operator.yml
  vars:
    subscription_name: '{{ rhacs_subscription_name }}'
    subscription_namespace: '{{ rhacs_subscription_namespace }}'

- name: Create temporary kustomize directory
  tempfile:
    state: directory
    suffix: -rhacs-kustomize
  register: tmpdir

- debug:
    msg: Created temporary directory {{ tmpdir.path }}

- name: Copy kustomization config to {{ tmpdir.path }}
  template:
    src: '{{ item }}'
    dest: '{{ tmpdir.path }}'
  with_items:
    - kustomization.yaml
    - central-htpasswd-secret.yaml
    - stackrox-central-services-central.yaml

- name: Install RHACS Central
  shell: kustomize build {{ tmpdir.path }} | oc apply --filename -

- name: Delete temporary kustomize directory {{ tmpdir.path }}
  file:
    path: '{{ tmpdir.path }}'
    state: absent
