- name: Set hostname if it was not set properly
  command: hostnamectl set-hostname {{ ansible_ssh_host }}
  when: ansible_nodename != ansible_ssh_host
  become: yes

- name: Set transient hostname if it was not set properly
  command: hostnamectl set-hostname --transient {{ ansible_ssh_host }}
  when: ansible_nodename != ansible_ssh_host
  register: hostname
  become: yes

- name: Run setup after the hostname changed
  setup:
  when: hostname is changed

- name: Add 127.0.0.1 entry to /etc/hosts
  lineinfile: dest=/etc/hosts line="127.0.0.1 {{ ansible_hostname }} {{ ansible_nodename }}"
  become: yes
