- include: disable_password_expiration.yml

- include: configure_sudo.yml

- include: generate_ssh_keys.yml

- include: configure_ntp.yml

- include: display_boot.yml

- include: fix_hostname.yml

- include: enable_core_dump.yml

- include: install_tools.yml
