- name: Configure ESXi host
  vmware_host_config_manager:
    hostname: '{{ vsphere_lab.esxi_hostname }}'
    username: '{{ vsphere_lab.esxi_username }}'
    password: '{{ vsphere_lab.esxi_password }}'
    esxi_hostname: '{{ vsphere_lab.esxi_hostname }}'
    options:
      'VMkernel.Boot.disableHwrng': 'true'
    validate_certs: False
  register: esxi_config

- name: Reboot ESXi for configuration changes to take effect
  vmware_host_powerstate:
    hostname: '{{ vsphere_lab.esxi_hostname }}'
    username: '{{ vsphere_lab.esxi_username }}'
    password: '{{ vsphere_lab.esxi_password }}'
    esxi_hostname: '{{ vsphere_lab.esxi_hostname }}'
    state: reboot-host
    force: True
    validate_certs: False
  when: esxi_config is changed

- name: Wait for ESXi host to start rebooting
  pause:
    seconds: 30
  when: esxi_config is changed

- name: Waiting since {{ lookup("pipe", "date +%r") }} for {{ vsphere_lab.esxi_hostname }} to come back up
  uri:
    url: 'https://{{ vsphere_lab.esxi_hostname }}'
    validate_certs: False
  register: result
  until: result.status == 200
  retries: 60
  delay: 10
