- name: Create Datacenter
  vmware_datacenter:
    hostname: '{{ vsphere_lab.vsphere_hostname }}'
    username: '{{ vsphere_lab.vsphere_username }}'
    password: '{{ vsphere_lab.vsphere_password }}'
    datacenter_name: Datacenter
    state: present
    validate_certs: False

- name: Create Cluster
  vmware_cluster:
    hostname: '{{ vsphere_lab.vsphere_hostname }}'
    username: '{{ vsphere_lab.vsphere_username }}'
    password: '{{ vsphere_lab.vsphere_password }}'
    datacenter_name: Datacenter
    cluster_name: Cluster
    validate_certs: False

- name: Add ESXi Host to vCenter
  vmware_host:
    hostname: '{{ vsphere_lab.vsphere_hostname }}'
    username: '{{ vsphere_lab.vsphere_username }}'
    password: '{{ vsphere_lab.vsphere_password }}'
    datacenter: Datacenter
    cluster: Cluster
    esxi_hostname: '{{ vsphere_lab.esxi_hostname }}'
    esxi_username: '{{ vsphere_lab.esxi_username }}'
    esxi_password: '{{ vsphere_lab.esxi_password }}'
    state: present
    validate_certs: False
