- set_fact:
    download_directory: /usr/local/share/ca-certificates/vsphere

- name: Ensure certificate directory exists
  file:
    path: '{{ download_directory }}'
    state: directory
  become: True

- name: Download CA certificates from https://{{ vsphere_lab.vsphere_hostname }}/certs/download.zip
  get_url:
    url: 'https://{{ vsphere_lab.vsphere_hostname }}/certs/download.zip'
    dest: '{{ download_directory }}'
    validate_certs: False
  become: True

- name: Download CA certificates from https://{{ vsphere_lab.vsphere_hostname }}/certs/download.zip
  unarchive:
    src: '{{ download_directory }}/download.zip'
    dest: '{{ download_directory }}'
    remote_src: True
  register: vsphere_certs
  become: True

- name: Update CA Trust
  command: update-ca-certificates
  when: vsphere_certs is changed
  become: True

- name: Check that certificates are trusted (this will fail if not)
  get_url:
    url: 'https://{{ vsphere_lab.vsphere_hostname }}/certs/download.zip'
    dest: '{{ download_directory }}'
    validate_certs: True
  become: True
