- name: Retrieve vCSA virtual machine
  import_tasks: retrieve_vcsa.yml

- name: Deploy vCenter Server Appliance
  import_tasks: deploy_vcenter.yml
  when: vcsa_vm is failed

- name: Retrieve vCSA virtual machine
  import_tasks: retrieve_vcsa.yml

- name: Reconfigure vCSA instance if needed
  import_tasks: configure_vcsa_vm.yml
  when: >
    vcsa_vm.instance.hw_memtotal_mb != vsphere_lab.vcsa_vm.memory
    or vcsa_vm.instance.hw_eth0.macaddress != vsphere_lab.vcsa_vm.macaddr

- name: Configure ESXi
  import_tasks: configure_esxi.yml

- name: Configure custom TLS certificates
  import_tasks: configure_certs_for_vcenter.yml

- name: Ensure vCSA autostarts
  import_tasks: vcsa_autostart.yml

- name: Creae ESXi cluster
  import_tasks: create_esxi_cluster.yml

- name: Install OpenShift deployment prerequisites
  import_tasks: ensure_openshift_prereqs.yml
