- name: Waiting since {{ lookup("pipe", "date +%r") }} for {{ vsphere_lab.vcenter_hostname }} to come back up
  uri:
    url: 'https://{{ vsphere_lab.vcenter_hostname }}'
    validate_certs: False
  register: result
  until: result.status == 200
  retries: 60
  delay: 10
