apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: contour-scc
  namespace: contour
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: contour-scc
subjects:
- kind: ServiceAccount
  name: contour
- kind: ServiceAccount
  name: contour-certgen
- kind: ServiceAccount
  name: envoy
