apiVersion: v1
kind: Secret
metadata:
  name: central-htpasswd
stringData:
  password: {{ generic_user_password }}
  htpasswd: admin:{{ generic_user_password | string | password_hash('bcrypt', 'constant1234567890123.') }}
type: Opaque
