apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rhacs-central

bases:
- {{ rhacs_kustomizations.instance }}

resources:
- central-htpasswd-secret.yaml

patchesStrategicMerge:
- stackrox-central-services-central.yaml
