apiVersion: platform.stackrox.io/v1alpha1
kind: Central
metadata:
  name: stackrox-central-services
spec:
  central:
    adminPasswordSecret:
      name: central-htpasswd
    defaultTLSSecret:
      name: central-tls
{% if rhacs_additional_trusted_ca is defined %}
  tls:
    additionalCAs:
      - name: custom_trusted_ca
        content: |
          {{ rhacs_additional_trusted_ca | indent(10) }}
{% endif %}
