apiVersion: platform.stackrox.io/v1alpha1
kind: Central
metadata:
  name: stackrox-central-services
spec:
  central:
    adminPasswordSecret:
      name: central-htpasswd
    defaultTLSSecret:
      name: central-tls
