- name: Install tools
  yum:
    name:
      - bind-utils # dig, host
      - bzip2
      - curl
      - gdb
      - git
      - jq
      - lsof
      - man-db
      - mc
      - net-tools
      - nmap-ncat
      - patch
      - strace
      - tcpdump
      - vim
      - wget
      - wireshark-cli
      - setroubleshoot-server # sealert
      - setools-console # sesearch
    state: present
  when: ansible_distribution in [ "RedHat", "Fedora" ]
  become: True

- name: Install tools RHEL7
  yum:
    name:
      - policycoreutils-python # semanage
    state: present
  when: ansible_distribution == "RedHat" and ansible_distribution_major_version | int <= 7
  become: True

- name: Install tools RHEL8
  yum:
    name:
      - policycoreutils-python-utils # semanage
      - python3-pygments
      - iotop
      - tmux
    state: present
  when: ansible_distribution == "RedHat" and ansible_distribution_major_version | int >= 8
  become: True

- name: Install tools Fedora
  yum:
    name:
      - colordiff
      - fzf
      - python3-pygments
      - htop
      - iotop
      - ngrep
      - ranger
      - tig
      - tmux
    state: present
  when: ansible_distribution == "Fedora"
  become: True

- name: Install tools used by ranger
  yum:
    name:
      - atool
      - python3-pygments
      - unoconv
      - mediainfo
  when: ansible_distribution == "Fedora"
  become: True
