- name: Try to detect the default ingress domain
  k8s_info:
    api_version: config.openshift.io/v1
    kind: Ingress
    name: cluster
    namespace: ''
  when: not ingress_domain
  register: openshift_config

- name:
  set_fact:
    ingress_domain: '{{ openshift_config.resources.0.spec.domain | default(ingress_domain) }}'

- name: Create a Quay project
  k8s:
    definition: "{{ lookup('template', 'quay-project.yml') }}"

- name: Create OperatorGroup object
  k8s:
    definition: "{{ lookup('template', 'quay-operatorgroup.yml') }}"

- name: Subscribe to Quay
  k8s:
    definition: "{{ lookup('template', 'quay-subscription.yml') }}"

- name: Create Red Hat Quay pull secret
  k8s:
    definition: "{{ lookup('template', 'redhat-quay-pull-secret-secret.yml') }}"

- name: Configure Quay super user
  k8s:
    definition: "{{ lookup('template', 'superuser-secret.yml') }}"

- name: Configure Quay configuration interface password
  k8s:
    definition: "{{ lookup('template', 'quayconfig-secret.yml') }}"

- name: Configure Quay database credentials
  k8s:
    definition: "{{ lookup('template', 'database-secret.yml') }}"

- name: Install Quay
  k8s:
    definition: "{{ lookup('template', 'quay-quayecosystem.yml') }}"
    wait: true
    wait_timeout: 600
    wait_condition:
      type: QuaySetupSuccess
      status: "True"

- name: Subscribe all namespaces to Container Security Operator
  k8s:
    definition: "{{ lookup('template', 'container-security-operator-subscription.yml') }}"
