- name: Try to detect the default ingress domain
  k8s_info:
    api_version: config.openshift.io/v1
    kind: Ingress
    name: cluster
    namespace: ''
  when: not ingress_domain
  register: openshift_config

- name:
  set_fact:
    ingress_domain: '{{ openshift_config.resources.0.spec.domain | default(ingress_domain) }}'

- name: Install Container Security Operator
  command: oc apply --kustomize {{ quay_kustomizations.security }}

- name: Deploy Quay operator
  command: oc apply --kustomize {{ quay_kustomizations.operator }}

- name: Create temporary kustomize directory
  tempfile:
    state: directory
    suffix: -quay-kustomize
  register: tmpdir

- debug:
    msg: Created temporary directory {{ tmpdir.path }}

- name: Copy kustomization config to {{ tmpdir.path }}
  template:
    src: '{{ item }}'
    dest: '{{ tmpdir.path }}'
  with_items:
    - kustomization.yaml
    - quay-quayecosystem.yaml
    - redhat-quay-pull-secret.json

- name: Install Quay
  command: oc apply --kustomize {{ tmpdir.path }}

- name: Delete temporary kustomize directory {{ tmpdir.path }}
  file:
    path: '{{ tmpdir.path }}'
    state: absent

- name: Waiting since {{ lookup("pipe", "date +%r") }} for Quay deployment to complete
  k8s_info:
    api_version: redhatcop.redhat.io/v1alpha1
    kind: QuayEcosystem
    namespace: '{{ quay_instance_namespace }}'
  register: quayecosystem
  until:
    - quayecosystem.resources.0.status is defined
    - quayecosystem.resources.0.status.conditions | selectattr('type', 'equalto', 'QuaySetupSuccess') | list | length > 0
    - (quayecosystem.resources.0.status.conditions | selectattr('type', 'equalto', 'QuaySetupSuccess') | first).status == 'True'
  failed_when: False
  retries: 60
  delay: 10
