- name: Obtain Quay registry route
  k8s_info:
    api_version: route.openshift.io/v1
    kind: Route
    name: '{{ quay_instance_name }}-quay'
    namespace: '{{ quay_instance_namespace }}'
  register: quay_instance_route

- name: Waiting since {{ lookup("pipe", "date +%r") }} for Quay to come up
  uri:
    url: 'https://{{ quay_instance_route.resources.0.spec.host }}/api/v1/discovery'
    method: GET
    validate_certs: False
  register: result
  until: result.status == 200
  retries: 60
  delay: 10

- debug:
    msg: Red Hat Quay installed successfully. Use your browser to access the Quay Web UI and create account for user admin. https://{{ quay_instance_route.resources.0.spec.host }}
