- name: Configure passwordless sudo
  import_role:
    name: common_tasks
    tasks_from: configure_passwordless_sudo.yml

- name: Configure common users
  import_role:
    name: common_tasks
    tasks_from: configure_common_users.yml

- name: Set authorized key for users
  authorized_key:
    user: '{{ item }}'
    key: '{{ lookup("file", lookup("env", "HOME") + "/.ssh/id_rsa.pub") }}'
  with_items:
    - root
    - ansible
    - developer
  become: True

- name: Set timezone to {{ time_zone }}
  timezone:
    name: '{{ time_zone }}'
  become: True

- name: Set UseDNS to no in sshd config
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^UseDNS'
    line: UseDNS no
  become: True

- name: Install SSH host keys
  import_tasks: install_ssh_host_keys.yml

- name: Configure cloud-init
  import_tasks: configure_cloud_init.yml

- name: Fix SELinux label on first boot
  copy:
    dest: /.autorelabel
    content: ''
    force: False
  become: True
