- name: Obtain infrastructure info
  k8s_info:
    api_version: config.openshift.io/v1
    kind: Infrastructure
    name: cluster
    namespace: ''
  register: infrastructure

- name: Set cluster_id
  set_fact:
    cluster_id: '{{ infrastructure.resources.0.status.infrastructureName }}'

- name: Add machine sets to the cluster
  k8s:
    definition: '{{ lookup("template", "workergpu-machineset.yml") }}'
  with_items: '{{ nvidia_gpu_availability_zones }}'

- name: Wait for the nodes to join the cluster
  import_role:
    name: openshift_common
    tasks_from: wait_for_nodes.yml
  vars:
    expand_machine_selector: machine.openshift.io/cluster-api-machine-role=workergpu
    expand_node_selector: node-role.example.com/workergpu=
    expand_nodes_total: '{{ nvidia_gpu_nodes_total }}'
