apiVersion: v1
kind: Secret
metadata:
  name: pull-secret
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: '{{ openshift_pull_secret.resources.0.data[".dockerconfigjson"] | b64decode }}'
