apiVersion: v1
kind: Secret
metadata:
  name: thanos-object-storage
stringData:
  thanos.yaml: |
    type: s3
    config:
      bucket: {{ rhacm_observability_s3_bucket }}
      endpoint: {{ rhacm_observability_s3_endpoint }}
      access_key: {{ rhacm_observability_s3_access_key }}
      secret_key: {{ rhacm_observability_s3_secret_key }}
      insecure: false
      http_config:
        insecure_skip_verify: true
