- name: Set admin user password
  k8s:
    definition: "{{ lookup('template', '{{ gitops_instance_name }}-cluster-secret.yaml') }}"

- name: Configure TLS edge-terminated route instead of passthrough
  k8s:
    definition: "{{ lookup('template', '{{ gitops_instance_name }}-argocd.yaml') }}"

- name: Configure Argo CD server
  k8s:
    definition: "{{ lookup('template', 'argocd-cm-cm.yaml') }}"
