- name: Obtain Argo CD route
  k8s_info:
    api_version: route.openshift.io/v1
    kind: Route
    name: '{{ argocd_instance_name }}-server'
    namespace: '{{ argocd_instance_namespace }}'
  register: argocd_route

- name: Configure Argo CD server
  k8s:
    definition: "{{ lookup('template', item) }}"
  loop:
    - argocd-keycloakrealm.yaml
    - argocd-keycloakclient.yaml
