- name: Delete GitOps operator
  command: oc delete --kustomize {{ gitops_kustomizations.operator }}

- import_role:
    name: openshift_common
    tasks_from: delete_kubernetes_objects.yml
  vars:
    delete_kubernetes_objects:
      - api_version: v1
        kind: Namespace
        name: openshift-gitops
