- name: Install the cri-o container runtime
  yum:
    name:
      - conmon
      - cri-o
      - oci-systemd-hook
      - runc
    enablerepo: rhocp-4.9-for-rhel-8-x86_64-rpms
  become: True

- name:
  ini_file:
    dest: /etc/crio/crio.conf
    section: crio.runtime
    option: conmon
    value: '"/usr/bin/conmon"'
  notify: Restart crio
  become: True

- name: Start crio service
  service:
    name: crio
    state: started
    enabled: True
  become: True
