- name: Install chrony package
  package: name={{ item }} state=installed
  loop:
    - chrony
  become: yes

- name: Enable chronyd service and start it
  service: name=chronyd state=started enabled=yes
  become: yes

- name: Refresh Ansible's ansible_date_time fact
  setup: filter=ansible_date_time
