- name: Configure passwordless sudo
  import_role:
    name: common_tasks
    tasks_from: configure_passwordless_sudo.yml

- name: Subscribe RHEL
  import_role:
    name: common_tasks
    tasks_from: subscribe_rhel.yml

- include: disable_password_expiration.yml

- include: set_ssh_authorized_keys.yml

- include: generate_ssh_keys.yml

- import_tasks: set_timezone.yml
  when: timezone | length > 0

- include: configure_ntp.yml

- include: display_boot.yml
  when: ansible_distribution == "RedHat"

- include: fix_hostname.yml

- include: enable_core_dump.yml

- name: Install tools
  import_role:
    name: common_tasks
    tasks_from: install_tools.yml

- name: Upgrade all packages
  import_role:
    name: common_tasks
    tasks_from: upgrade_all_packages.yml
