apiVersion: config.openshift.io/v1
kind: APIServer
metadata:
  name: cluster
spec:
  servingCerts:
    namedCertificates:
    - names:
      - {{ openshift_cluster_certs.api.domain }}
      servingCertificate:
        name: api-cert
