otlc_service_catalog_id: '20000000000040'
otlc_service_catalog_name: 'OPENTLC OpenShift 4 Labs'
otlc_service_template_id: '20000000000619'
otlc_service_template_name: 'OpenShift 4 Installation Lab'
otlc_service_options: {}
